## TASK 10 - Loandata Case Study
> + Name : Anvesh Hirve
> + Batch no : 550
> + Module : EDA - Exploratory Data Analysis

In [4]:
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [69]:
df = pd.read_csv(r"C:\Users\Anvesh\OneDrive\Desktop\Innomatics Research Labs Module\EDA_550\data\data\loandata.csv")

In [70]:
df

,Unnamed: 0,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
976,976,LP002971,Male,Yes,3+,Not Graduate,Yes,4009,1777.0,113.0,360.0,1.0,Urban,NaN
977,977,LP002975,Male,Yes,0,Graduate,No,4158,709.0,115.0,360.0,1.0,Urban,NaN
978,978,LP002980,Male,No,0,Graduate,No,3250,1993.0,126.0,360.0,NaN,Semiurban,NaN
979,979,LP002986,Male,Yes,0,Graduate,No,5000,2393.0,158.0,360.0,1.0,Rural,NaN
980,980,LP002989,Male,No,0,Graduate,Yes,9200,0.0,98.0,180.0,1.0,Rural,NaN

#### 1. Display the first 5 rows of the DataFrame using head().

In [71]:
df.head(5)

,Unnamed: 0,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [72]:
# Display the unique values in the Gender column.
df['Gender'].unique()

array(['Male', 'Female', nan], dtype=object)

#### 2. Group the DataFrame by the Gender column and calculate the mean of ApplicantIncome for each gender using groupby().

In [73]:
df.groupby('Gender')['ApplicantIncome'].mean()

Gender
Female    4458.906593
Male      5256.925161
Name: ApplicantIncome, dtype: float64

In [74]:
# Calculate the minimum LoanAmount for each Education category using groupby().
df.groupby('Education')['LoanAmount'].min()

Education
Graduate         9.0
Not Graduate    25.0
Name: LoanAmount, dtype: float64

#### 3. Group the DataFrame by both Gender and Married columns, and calculate the maximum LoanAmount and mean ApplicantIncome using agg().

In [75]:
df.groupby(['Gender', 'Married']).agg({
    'LoanAmount': 'max',
    'ApplicantIncome': 'mean'
})

                LoanAmount  ApplicantIncome
Gender Married
Female No            350.0      4394.153226
       Yes           600.0      4501.736842
Male   No            650.0      4912.764151
       Yes           600.0      5390.440285

In [76]:
# Calculate the count, variance, and standard deviation of LoanAmount for each Property_Area using .agg([np.var, np.max, np.std, np.min,np.max, np.count_nonzero])
import warnings
warnings.filterwarnings('ignore')
df.groupby('Property_Area')['LoanAmount'].agg([np.var, np.max, np.std, np.min,np.max, np.count_nonzero])

                       var    max        std   min    max  count_nonzero
Property_Area
Rural          5202.898153  570.0  72.131118  28.0  570.0            290
Semiurban      5734.891187  600.0  75.729064  25.0  600.0            349
Urban          6955.987786  700.0  83.402565   9.0  700.0            342

#### 4. Sort the DataFrame by LoanAmount in descending order

In [77]:
df['LoanAmount'].isnull().sum()

np.int64(27)

In [78]:
df['LoanAmount'] = df['LoanAmount'].fillna(df['LoanAmount'].mean())

In [79]:
df['LoanAmount'].isnull().sum()

np.int64(0)

In [80]:
df['LoanAmount'].sort_values(ascending=False)

171    700.0
130    650.0
561    600.0
155    600.0
369    570.0
       ...
555     26.0
133     25.0
94      25.0
14      17.0
568      9.0
Name: LoanAmount, Length: 981, dtype: float64

In [81]:
# find the number of applicants with different Loan_Status values.
df.groupby('Loan_Status').size()

Loan_Status
N    192
Y    422
dtype: int64

#### 5. Create a cross-tabulation of Gender and Loan_Status to see the count of loan approvals based on gender using crosstab().

In [82]:
pd.crosstab(df['Gender'],df['Loan_Status'])

Loan_Status    N    Y
Gender
Female        37   75
Male         150  339

#### 6. Create a pivot table that shows the average LoanAmount for each combination of Education and Property_Area.

In [83]:
df.pivot_table(index='Education',columns='Property_Area',values='LoanAmount',aggfunc='mean')

Property_Area       Rural   Semiurban       Urban
Education
Graduate       155.097436  147.899930  145.637701
Not Graduate   122.128846  119.053333  116.703734

#### 7. Sort the DataFrame by ApplicantIncome in ascending order, then by LoanAmount in descending order using sort_values().

In [84]:
df[['ApplicantIncome','LoanAmount']].sort_values(['ApplicantIncome','LoanAmount'],ascending=[True,False]).head(10)

     ApplicantIncome  LoanAmount
730                0       180.0
639                0       148.0
216              150       135.0
468              210        98.0
600              416       350.0
917              570        68.0
500              645       113.0
188              674       168.0
733              724       213.0
77              1000       110.0

In [85]:
# Create a pivot table to calculate the sum of LoanAmount for each Self_Employed status, grouped by Gender.
df.pivot_table(index='Gender',columns='Self_Employed',values='LoanAmount',aggfunc='sum')

Self_Employed            No           Yes
Gender
Female         18361.534591   3213.511530
Male           90596.230608  15351.023061

#### 8. Check for missing values in the dataset using isnull() and notnull().

In [86]:
df.isnull().sum()

Unnamed: 0             0
Loan_ID                0
Gender                24
Married                3
Dependents            25
Education              0
Self_Employed         55
ApplicantIncome        0
CoapplicantIncome      0
LoanAmount             0
Loan_Amount_Term      20
Credit_History        79
Property_Area          0
Loan_Status          367
dtype: int64

In [87]:
df.notnull().sum()

Unnamed: 0           981
Loan_ID              981
Gender               957
Married              978
Dependents           956
Education            981
Self_Employed        926
ApplicantIncome      981
CoapplicantIncome    981
LoanAmount           981
Loan_Amount_Term     961
Credit_History       902
Property_Area        981
Loan_Status          614
dtype: int64

In [88]:
# Calculate the percentage of missing values for each column.
(df.isnull().sum()/len(df))*100

Unnamed: 0            0.000000
Loan_ID               0.000000
Gender                2.446483
Married               0.305810
Dependents            2.548420
Education             0.000000
Self_Employed         5.606524
ApplicantIncome       0.000000
CoapplicantIncome     0.000000
LoanAmount            0.000000
Loan_Amount_Term      2.038736
Credit_History        8.053007
Property_Area         0.000000
Loan_Status          37.410805
dtype: float64

#### 9. Fill missing values in the Gender and Married columns with the mode of the respective column.

In [89]:
df['Gender'].isnull().sum()

np.int64(24)

In [90]:
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

In [93]:
df['Gender'].isnull().sum()

np.int64(0)

In [91]:
df['Married'].isnull().sum()

np.int64(3)

In [92]:
df['Married'] = df['Married'].fillna(df['Married'].mode()[0])

In [94]:
df['Married'].isnull().sum()

np.int64(0)

In [96]:
# Replace missing values in the LoanAmount column with the mean value.
df['LoanAmount'] = df['LoanAmount'].fillna(df['LoanAmount'].mean())

In [97]:
df['LoanAmount'].isnull().sum()

np.int64(0)

In [98]:
# Drop rows where Credit_History is missing
df['Credit_History'].isnull().sum()

np.int64(79)

In [99]:
df = df.dropna(subset=['Credit_History'])

In [100]:
df['Credit_History'].isnull().sum()

np.int64(0)

#### 10. Reset the index of the loanddata dataset using reset_index() and ensure the old index is not retained

In [103]:
df

,Unnamed: 0,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,0,LP001002,Male,No,0,Graduate,No,5849,0.0,142.51153,360.0,1.0,Urban,Y
1,1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.00000,360.0,1.0,Rural,N
2,2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.00000,360.0,1.0,Urban,Y
3,3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.00000,360.0,1.0,Urban,Y
4,4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.00000,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
975,975,LP002969,Male,Yes,1,Graduate,No,2269,2167.0,99.00000,360.0,1.0,Semiurban,NaN
976,976,LP002971,Male,Yes,3+,Not Graduate,Yes,4009,1777.0,113.00000,360.0,1.0,Urban,NaN
977,977,LP002975,Male,Yes,0,Graduate,No,4158,709.0,115.00000,360.0,1.0,Urban,NaN
979,979,LP002986,Male,Yes,0,Graduate,No,5000,2393.0,158.00000,360.0,1.0,Rural,NaN
980,980,LP002989,Male,No,0,Graduate,Yes,9200,0.0,98.00000,180.0,1.0,Rural,NaN

In [104]:
df.reset_index()

,index,Unnamed: 0,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,0,0,LP001002,Male,No,0,Graduate,No,5849,0.0,142.51153,360.0,1.0,Urban,Y
1,1,1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.00000,360.0,1.0,Rural,N
2,2,2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.00000,360.0,1.0,Urban,Y
3,3,3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.00000,360.0,1.0,Urban,Y
4,4,4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.00000,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
897,975,975,LP002969,Male,Yes,1,Graduate,No,2269,2167.0,99.00000,360.0,1.0,Semiurban,NaN
898,976,976,LP002971,Male,Yes,3+,Not Graduate,Yes,4009,1777.0,113.00000,360.0,1.0,Urban,NaN
899,977,977,LP002975,Male,Yes,0,Graduate,No,4158,709.0,115.00000,360.0,1.0,Urban,NaN
900,979,979,LP002986,Male,Yes,0,Graduate,No,5000,2393.0,158.00000,360.0,1.0,Rural,NaN
901,980,980,LP002989,Male,No,0,Graduate,Yes,9200,0.0,98.00000,180.0,1.0,Rural,NaN

#### 11. Count the unique values in the Gender and Married columns.

In [107]:
df['Gender'].nunique()

2

In [108]:
df['Married'].nunique()

2

In [109]:
# Find the average loan amount and loan term after handling missing values.
df['LoanAmount'].isnull().sum()

np.int64(0)

In [110]:
df['Loan_Amount_Term'].isnull().sum()

np.int64(19)

In [111]:
df['Loan_Amount_Term'] = df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].mean())

In [112]:
df['Loan_Amount_Term'].isnull().sum()

np.int64(0)

In [113]:
df[['LoanAmount','Loan_Amount_Term']].mean()

LoanAmount          141.806319
Loan_Amount_Term    342.083805
dtype: float64

#### 12.

In [5]:
data = {'Loan_ID': [f'LP00{i}' for i in range(1, 11)],
'Gender': ['Male', 'Female', np.nan, 'Male', 'Female', np.nan, 'Male', 'Female', 'Female', 'Male'],
'Married': ['No', 'Yes', 'Yes', np.nan, 'Yes', 'No', 'Yes', 'No', np.nan, 'Yes'],
'LoanAmount': [250, 120, 300, np.nan, 180, np.nan, 400, 200, 150, np.nan],
'Loan_Amount_Term': [360, 360, 120, 180, np.nan, 360, np.nan, 240, 360, 180],
'Credit_History': [1.0, 0.0, 1.0, np.nan, 1.0, 0.0, 1.0, np.nan, 1.0, 0.0],
'Date_Of_Application': pd.date_range(start='2025-01-01', periods=10, freq='D')}

In [6]:
df = pd.DataFrame(data)

In [7]:
df

,Loan_ID,Gender,Married,LoanAmount,Loan_Amount_Term,Credit_History,Date_Of_Application
0,LP001,Male,No,250.0,360.0,1.0,2025-01-01
1,LP002,Female,Yes,120.0,360.0,0.0,2025-01-02
2,LP003,NaN,Yes,300.0,120.0,1.0,2025-01-03
3,LP004,Male,NaN,NaN,180.0,NaN,2025-01-04
4,LP005,Female,Yes,180.0,NaN,1.0,2025-01-05
5,LP006,NaN,No,NaN,360.0,0.0,2025-01-06
6,LP007,Male,Yes,400.0,NaN,1.0,2025-01-07
7,LP008,Female,No,200.0,240.0,NaN,2025-01-08
8,LP009,Female,NaN,150.0,360.0,1.0,2025-01-09
9,LP0010,Male,Yes,NaN,180.0,0.0,2025-01-10

In [10]:
# Extract the year and month from the Date_Of_Application column.
year = df['Date_Of_Application'].dt.year
month = df['Date_Of_Application'].dt.month_name()

In [11]:
print(year,month)

0    2025
1    2025
2    2025
3    2025
4    2025
5    2025
6    2025
7    2025
8    2025
9    2025
Name: Date_Of_Application, dtype: int32 0    January
1    January
2    January
3    January
4    January
5    January
6    January
7    January
8    January
9    January
Name: Date_Of_Application, dtype: object

In [12]:
# Create a custom date range for 5 future dates starting from the last date in the Date_Of_Application column.
start_date = df['Date_Of_Application'].iloc[-1] + pd.Timedelta(days=1)
date_range = pd.date_range(start=start_date, periods=5)

print(date_range)

DatetimeIndex(['2025-01-11', '2025-01-12', '2025-01-13', '2025-01-14',
               '2025-01-15'],
              dtype='datetime64[ns]', freq='D')

#### 13.

In [13]:
dic={'Gender':['Male','Female','Male','Female','Male',"Male"],
         'Married':['Yes','No','No','No','Yes',"Yes"],
         'Loan_Status':['Yes','No','No','No','Yes',"Yes"]}

In [14]:
df = pd.DataFrame(dic)

In [16]:
# Check for duplicate rows in the dataset using duplicated(keep='first').
df.duplicated(keep='first')

0    False
1    False
2    False
3     True
4     True
5     True
dtype: bool

In [18]:
# Drop duplicate rows from the dataset using drop_duplicates().
df.drop_duplicates()

   Gender Married Loan_Status
0    Male     Yes         Yes
1  Female      No          No
2    Male      No          No